from pathlib import Path
import subprocess
import unittest


ROOT = Path(__file__).resolve().parents[1]


class MobileAgentUiContractTests(unittest.TestCase):
    def test_mobile_agent_module_is_loaded(self):
        loader = (ROOT / "static/js/module_loader.js").read_text()

        self.assertIn("/modules/mobile_agent/mobile-agent.js?v=", loader)
        self.assertIn("static/css/mobile-agent.css?v=", loader)
        self.assertIn("var mobileCoreModules = [", loader)
        self.assertIn("var desktopCoreModules = [", loader)
        self.assertIn("var modulesToLoad = isMobileAgentPath ? mobileCoreModules : desktopCoreModules;", loader)
        self.assertLess(loader.index("/modules/generate.js?v="), loader.index("/modules/mobile_agent/mobile-agent.js?v="))
        mobile_block = loader[loader.index("var mobileCoreModules = ["):loader.index("var loggedInModules")]
        self.assertNotIn("/modules/generate.js?v=", mobile_block)
        self.assertNotIn("/modules/workflows.js?v=", mobile_block)
        self.assertNotIn("/modules/history.js?v=", mobile_block)
        self.assertNotIn("/app.js?v=", mobile_block)
        self.assertIn("function initMobileSharedApp()", loader)
        self.assertIn("if (isMobileAgentPath) initMobileSharedApp();", loader)

    def test_mobile_agent_app_path_uses_shared_comfy_job_backend(self):
        loader = (ROOT / "static/js/module_loader.js").read_text()
        js = (ROOT / "static/js/modules/mobile_agent/mobile-agent.js").read_text()

        self.assertIn("window.CW_MOBILE_API_BASE = '/app'", loader)
        self.assertIn("window.CW_JOB_API_BASE = '/comfy'", loader)
        self.assertIn("var JOB_API = window.CW_JOB_API_BASE", js)
        self.assertIn("authFetch(JOB_API + '/api/generate'", js)
        self.assertIn("JOB_API + '/api/images/'", js)

    def test_mobile_agent_root_exists(self):
        html = (ROOT / "static/index.html").read_text()

        self.assertIn('<main class="mobile-agent hidden" id="mobileAgentRoot" aria-label="移动端智能创作入口"></main>', html)
        self.assertIn("mobile-agent-boot", html)
        self.assertIn("html.mobile-agent-boot body > :not(#mobileAgentRoot)", html)
        self.assertIn('body[data-mobile-agent-active="on"] > :not(#mobileAgentRoot):not(.auth-modal-overlay)', html)

    def test_mobile_agent_module_renders_core_states(self):
        js = (ROOT / "static/js/modules/mobile_agent/mobile-agent.js").read_text()

        self.assertIn("function renderHome", js)
        self.assertIn("mobile-agent-boot", js)
        self.assertIn("document.documentElement.classList.add('mobile-agent-boot')", js)
        self.assertIn("function renderTopBar", js)
        self.assertIn("function renderThreadList", js)
        self.assertIn("function renderHistoryView", js)
        self.assertIn("function newChat", js)
        self.assertIn("function openThread", js)
        self.assertIn("function deleteThread", js)
        self.assertIn("function openLogin", js)
        self.assertIn("function syncAfterAuthReady", js)
        self.assertIn('data-action="login"', js)
        self.assertNotIn('<button type="button" data-action="new-chat">新建</button>', js)
        self.assertIn("window.CW.authReady.finally", js)
        self.assertIn("function renderVoice", js)
        self.assertIn("function renderConfirm", js)
        self.assertIn("function renderGenerating", js)
        self.assertIn("function renderConversation", js)
        self.assertIn("mobile-agent-conversation-footer", js)
        self.assertIn("function syncConversationChromeMetrics", js)
        self.assertIn("function syncTextAreaHeight", js)
        self.assertIn("function patchTaskMessageDom", js)
        self.assertIn("function onFocusIn", js)
        self.assertIn("state.root.addEventListener('focusin', onFocusIn);", js)
        self.assertIn("state.root.addEventListener('focusout', onFocusOut);", js)
        self.assertIn("is-input-blurring", js)
        self.assertIn("inputBlurTimer", js)
        self.assertIn("inputActiveTimer", js)
        self.assertIn("is-input-breathing", js)
        self.assertIn("is-aura-entering", js)
        self.assertIn("startAuraEnter", js)
        self.assertIn("auraEnterTimer", js)
        self.assertIn("new ResizeObserver", js)
        self.assertIn("function submitUnderstand", js)
        self.assertIn("function prepareHomeSubmitThread", js)
        self.assertIn("if (event.key !== 'Enter' || event.shiftKey) return;", js)
        self.assertIn("function uploadSourceImageAttachment", js)
        self.assertIn("function renderMarkdown", js)
        self.assertIn("function renderMessageAttachments", js)
        self.assertIn("/api/mobile-agent/upload-attachment", js)
        self.assertIn("function openMobileAgent", js)
        self.assertIn("function resultFromJob", js)
        self.assertIn("function loadRemoteThreads", js)
        self.assertIn("function syncThreadToServer", js)
        self.assertIn("function syncLocalThreadsToServer", js)
        self.assertIn("function bindMobileAuthRefreshHook", js)
        self.assertIn("function deleteThreadFromServer", js)
        self.assertIn("function refreshPendingJobState", js)
        self.assertIn("/api/mobile-agent/threads", js)
        self.assertIn("JOB_API + '/api/jobs/'", js)
        self.assertIn("job.pending_image", js)
        self.assertIn("firstArrayValue(job.images)", js)
        self.assertIn("firstBatchValue(job, 'filename')", js)
        self.assertIn("mobile-agent-chat", js)
        self.assertIn("mobile-agent-avatar", js)
        self.assertIn("mobile-agent-history-list", js)
        self.assertIn("data-action=\"open-history\"", js)
        self.assertIn("全部历史对话", js)
        self.assertIn("state.mode === 'history'", js)
        self.assertIn("mobile-agent-thread-delete", js)
        self.assertIn('placeholder="请输入对话内容"', js)
        self.assertIn("mobile-agent-plus-btn", js)
        self.assertIn("mobile-agent-send-icon-btn", js)
        self.assertIn("mobile-agent-confirm-card", js)
        self.assertIn("mobile-agent-task-card", js)
        self.assertIn("mobile-agent-task-description", js)
        self.assertIn("mobile-agent-task-actions", js)
        self.assertIn("mobile-agent-task-action mobile-agent-task-retry", js)
        self.assertIn("data-action=\"retry-generate\"", js)
        self.assertIn("THINKING_TIMEOUT_MS", js)
        self.assertIn("data-action=\"like-answer\"", js)
        self.assertIn("data-action=\"regenerate-answer\"", js)
        self.assertIn("data-action=\"delete-answer\"", js)
        self.assertIn("重点认可", js)
        self.assertIn("var generationSummary = data.display_summary || data.compiled_prompt || ''", js)
        self.assertIn("var generationPrompt = data.compiled_prompt || data.display_summary || ''", js)
        self.assertIn("task_description: generationSummary", js)
        self.assertIn("prompt_preview: generationPrompt", js)
        self.assertIn("mobile-agent-result-card", js)
        self.assertIn("function renderResultCard", js)
        self.assertIn("function renderResultPreviewOverlay", js)
        self.assertIn("data-action=\"open-result-preview\"", js)
        self.assertIn("data-action=\"toggle-result-prompt\"", js)
        self.assertIn("data-action=\"close-result-preview\"", js)
        self.assertIn("mobile-agent-confirm-main", js)
        self.assertIn("mobile-agent-option-block", js)
        self.assertIn("mobile-agent-workflow-status", js)
        self.assertIn("mobile-agent-workflow-switch", js)
        self.assertIn("mobile-agent-workflow-menu", js)
        self.assertIn("toggleWorkflowMenu", js)
        self.assertIn("data-action=\"toggle-workflow-menu\"", js)
        self.assertIn("/api/mobile-agent/understand", js)
        self.assertIn("/api/mobile-agent/transcribe", js)
        self.assertIn("CW.mobileAgent", js)
        self.assertIn("function icon", js)
        self.assertIn("icon('send'", js)
        self.assertIn("icon('mic'", js)
        self.assertNotIn("CW.icon('send'", js)
        self.assertNotIn("CW.icon('mic'", js)

    def test_mobile_agent_path_skips_desktop_boot_and_notifications(self):
        loader = (ROOT / "static/js/module_loader.js").read_text()
        ui_js = (ROOT / "static/js/modules/ui.js").read_text()
        auth_js = (ROOT / "static/js/modules/auth.js").read_text()

        self.assertIn("if (!isMobileAgentPath && window.CW._bootApp) window.CW._bootApp();", loader)
        self.assertIn("if (isMobileAgentPath) return;", loader)
        self.assertIn("if (mobileActive) return;", ui_js)
        self.assertIn("function _isMobileAgentRoute()", auth_js)
        self.assertIn("if (_isMobileAgentRoute()) return Promise.resolve(null);", auth_js)
        self.assertIn("if (_isMobileAgentRoute()) return;", auth_js)

    def test_generate_handoff_calls_existing_generate_api(self):
        js = (ROOT / "static/js/modules/mobile_agent/mobile-agent.js").read_text()

        self.assertIn("function submitGenerate", js)
        self.assertIn("/api/generate", js)
        self.assertIn("resolved_workflow", js)
        self.assertIn("workflow_choices", js)
        self.assertIn("creative_brief", js)
        self.assertIn("field_values", js)
        self.assertIn("width", js)
        self.assertIn("height", js)
        self.assertIn("handleJobUpdate", js)
        self.assertIn("getConversationContext", js)

    def test_mobile_agent_executable_behavior(self):
        result = subprocess.run(
            ["node", "tests/js/mobile_agent_shell.test.js"],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_mobile_agent_css_is_mobile_first_and_scoped(self):
        css = (ROOT / "static/css/mobile-agent.css").read_text()

        self.assertIn(".mobile-agent", css)
        self.assertIn(".mobile-agent.is-input-active::before", css)
        self.assertIn(".mobile-agent.is-input-active::after", css)
        self.assertIn(".mobile-agent-panel::before", css)
        self.assertIn("width='6' height='6'", css)
        self.assertIn("circle cx='2.5' cy='2.5' r='2.5' fill='%23000000'", css)
        self.assertIn("background-size: 6px 6px", css)
        self.assertIn("width: 160vmax", css)
        self.assertIn("height: 160vmax", css)
        self.assertIn("rotate(45deg)", css)
        self.assertIn(".mobile-agent-panel::after", css)
        self.assertIn("mobile-agent-top-aura", css)
        self.assertIn("rgba(184, 104, 148", css)
        self.assertIn("bottom: 0", css)
        self.assertIn("height: 28vh", css)
        self.assertIn("opacity: 0.56", css)
        self.assertIn("height: 48vh", css)
        self.assertIn("height: 44vh", css)
        self.assertIn("filter: blur(58px)", css)
        self.assertIn("mobile-agent-blue-aura-settle", css)
        self.assertIn("mobile-agent-blue-aura-ripple-out", css)
        self.assertIn("mobile-agent-blue-aura-enter", css)
        self.assertIn("mobile-agent-blue-aura-enter-ripple", css)
        self.assertIn("mobile-agent-blue-aura-focus-in", css)
        self.assertIn("mobile-agent-blue-aura-focus-in-ripple", css)
        self.assertIn(".mobile-agent.is-input-active.is-input-breathing::after", css)
        self.assertNotIn("mobile-agent-bg-breathe", css)
        self.assertNotIn("mobile-agent-bg-exhale", css)
        self.assertNotIn("mobile-agent-orb-brand", css)
        self.assertNotIn("mobile-agent-orb-user", css)
        self.assertNotIn("mobile-agent-orb-compose", css)
        self.assertIn(".mobile-agent-panel:has(.mobile-agent-menu.is-open)::after", css)
        self.assertIn("--mobile-surface: #17202b", css)
        self.assertIn("--mobile-surface-elevated: #1b2836", css)
        self.assertIn("--mobile-compose-glass: rgba(19, 20, 23, 0.78)", css)
        self.assertIn("backdrop-filter: blur(18px) saturate(1.18)", css)
        self.assertIn(".mobile-agent-message-assistant > div", css)
        self.assertIn("background: rgba(27, 40, 54, 0.72)", css)
        self.assertIn("backdrop-filter: blur(14px) saturate(1.12)", css)
        self.assertIn(".mobile-agent-workflow-switch", css)
        self.assertIn(".mobile-agent-workflow-menu", css)
        self.assertIn(".mobile-agent-compose::before", css)
        self.assertIn(".mobile-agent.is-input-active .mobile-agent-compose::before", css)
        self.assertIn(".mobile-agent.is-input-blurring .mobile-agent-compose::before", css)
        self.assertIn("mobile-agent-blue-aura-wave", css)
        self.assertIn("height: 34vh", css)
        self.assertIn(".mobile-agent-panel", css)
        self.assertIn(".mobile-agent-hero", css)
        self.assertIn("position: relative;\n  display: flex;\n  align-items: center;\n  justify-content: center;", css)
        self.assertIn(".mobile-agent-copy {\n  position: static;", css)
        self.assertIn(".mobile-agent-topbar", css)
        self.assertIn(".mobile-agent-avatar", css)
        self.assertIn(".mobile-agent-menu", css)
        self.assertIn(".mobile-agent-menu.is-open", css)
        self.assertIn(".mobile-agent-menu-logout", css)
        self.assertIn(".mobile-agent-history-list", css)
        self.assertIn(".mobile-agent-history-row", css)
        self.assertIn(".mobile-agent-history-title", css)
        self.assertIn(".mobile-agent-history-page", css)
        self.assertIn(".mobile-agent-history-page {\n  min-height: 0;\n  flex: 1 1 auto;\n  display: flex;\n  flex-direction: column;\n  gap: 16px;\n  padding-top: 18px;", css)
        self.assertIn('.mobile-agent-panel[data-view="history"]', css)
        self.assertIn(".mobile-agent-menu-thread-row", css)
        self.assertIn(".mobile-agent-thread-delete", css)
        self.assertIn(".mobile-agent-history-row .mobile-agent-thread-delete", css)
        self.assertIn(".mobile-agent-menu-thread-row .mobile-agent-thread-delete", css)
        self.assertIn("background: transparent", css)
        self.assertIn(".mobile-agent-chat", css)
        self.assertIn(".mobile-agent-conversation-footer", css)
        self.assertIn('.mobile-agent-panel[data-view="conversation"] .mobile-agent-topbar', css)
        self.assertIn("linear-gradient(180deg, #131314 0%, rgba(19, 19, 20, 0.86)", css)
        self.assertIn("linear-gradient(0deg, #131314 0%, rgba(19, 19, 20, 0.86)", css)
        self.assertIn("padding-bottom: var(--mobile-footer-space", css)
        self.assertIn("position: fixed", css)
        self.assertIn(".mobile-agent-message-user", css)
        self.assertIn(".mobile-agent-message-attachment", css)
        self.assertIn(".mobile-agent-markdown", css)
        self.assertIn(".mobile-agent-markdown h1", css)
        self.assertIn(".mobile-agent-markdown ol", css)
        self.assertIn(".mobile-agent-markdown blockquote", css)
        self.assertIn(".mobile-agent-markdown pre", css)
        self.assertIn("white-space: pre-wrap", css)
        self.assertIn(".mobile-agent-task-card", css)
        self.assertIn(".mobile-agent-task-card.is-error", css)
        self.assertIn(".mobile-agent-task-preview", css)
        self.assertIn(".mobile-agent-task-description", css)
        self.assertIn(".mobile-agent-task-actions", css)
        self.assertIn(".mobile-agent-answer-actions", css)
        self.assertIn(".mobile-agent-assistant-stack", css)
        self.assertIn(".mobile-agent-task-action", css)
        self.assertIn(".mobile-agent-answer-action.is-liked", css)
        self.assertIn("mobile-agent-shimmer", css)
        self.assertIn(".mobile-agent-result-card", css)
        self.assertIn(".mobile-agent-result-actions", css)
        self.assertIn(".mobile-agent-result-image-btn", css)
        self.assertIn(".mobile-agent-result-prompt", css)
        self.assertIn(".mobile-agent-preview-overlay", css)
        self.assertIn(".mobile-agent-preview-close", css)
        self.assertIn(".mobile-agent-input-row", css)
        self.assertIn(".mobile-agent-compose:focus-within", css)
        self.assertIn("max-height: 112px", css)
        self.assertIn("grid-template-columns: 48px minmax(0, 1fr) 44px 46px", css)
        self.assertIn(".mobile-agent-plus-btn", css)
        self.assertIn(".mobile-agent-compose .mobile-agent-send-btn", css)
        self.assertIn(".mobile-agent-panel[data-view=\"conversation\"] .mobile-agent-compose:focus-within", css)
        self.assertIn("--mobile-motion-duration: 300ms", css)
        self.assertIn("color: #15100a", css)
        self.assertIn(".mobile-agent-input-row.is-voice-active .mobile-agent-send-btn", css)
        self.assertIn("opacity 300ms ease", css)
        self.assertIn("transform: translate3d(0, -8px, 0) scale(0.97)", css)
        self.assertIn("grid-template-columns var(--mobile-motion-duration) ease", css)
        self.assertIn("transform var(--mobile-motion-duration) ease", css)
        self.assertIn("@media (max-width: 700px)", css)
        self.assertIn("height: calc(var(--vh, 1vh) * 100", css)
        self.assertIn("overflow-x: hidden", css)
        self.assertIn("position: fixed", css)


if __name__ == "__main__":
    unittest.main()
