import unittest

from modules.image_reverse.contracts import (
    REVERSE_MODE_ADVANCED,
    REVERSE_MODE_EXPERT,
    REVERSE_MODE_EXPERT_TEAM,
    REVERSE_MODE_STANDARD,
    ReverseOutput,
    mode_level,
    mode_token_budget,
)
from modules.image_reverse.prompts import (
    build_expert_prompt,
    build_expert_team_global_prompt,
    build_expert_team_review_prompt,
    build_expert_team_subject_prompt,
    build_standard_prompt,
)


class ImageReverseContractTests(unittest.TestCase):
    def test_modes_have_distinct_token_budgets(self):
        self.assertLess(mode_token_budget(REVERSE_MODE_STANDARD), mode_token_budget(REVERSE_MODE_EXPERT))
        self.assertLess(mode_token_budget(REVERSE_MODE_EXPERT), mode_token_budget(REVERSE_MODE_EXPERT_TEAM))
        self.assertEqual(mode_token_budget(REVERSE_MODE_ADVANCED), 5120)
        self.assertEqual(REVERSE_MODE_EXPERT, REVERSE_MODE_ADVANCED)
        self.assertEqual(mode_level(REVERSE_MODE_STANDARD), 0)
        self.assertEqual(mode_level(REVERSE_MODE_ADVANCED), 1)
        self.assertEqual(mode_level(REVERSE_MODE_EXPERT_TEAM), 2)

    def test_reverse_output_exports_compatible_payload(self):
        output = ReverseOutput(
            mode=REVERSE_MODE_EXPERT,
            provider="test-vision",
            prompt="主体位于画面中心，红色上衣，灰色背景",
            negative_prompt=["文字", "水印"],
            visual_spec={"画面描述": {"基本概述": "红色主题人物图"}},
            raw={"基本概述": "红色主题人物图"},
            expert_interrogate={"enabled": True, "mode": "expert", "experts": []},
        )

        payload = output.to_api_payload()

        self.assertEqual(payload["prompt"], "主体位于画面中心，红色上衣，灰色背景")
        self.assertEqual(payload["reverse_mode"], "advanced")
        self.assertEqual(payload["reverse_level"], 1)
        self.assertEqual(payload["reverse_mode_label"], "加强")
        self.assertEqual(payload["promptgen"], payload["prompt"])
        self.assertEqual(payload["prompt_zh"], payload["prompt"])
        self.assertNotIn("negative_prompt", payload)
        self.assertIn('"画面描述"', payload["structured_prompt_json"])
        self.assertTrue(payload["expert_interrogate"]["enabled"])

    def test_standard_prompt_is_compact_and_not_expert_team(self):
        prompt = build_standard_prompt()

        self.assertIn("标准：", prompt)
        self.assertIn("必须只输出图中直接看见的事实", prompt)
        self.assertIn("不得猜想", prompt)
        self.assertIn("整体描述", prompt)
        self.assertIn("肢体左右参照规则", prompt)
        self.assertIn("画面左侧手臂", prompt)
        self.assertIn("禁止单独使用“左手、右手", prompt)
        self.assertIn("背景", prompt)
        self.assertIn("前景", prompt)
        self.assertIn("最终提示词", prompt)
        self.assertNotIn("专家团第", prompt)
        self.assertNotIn("aa" + "、ab" + "、ac", prompt)
        self.assertNotIn("b" + "c", prompt)
        self.assertLess(len(prompt), 4200)

    def test_expert_prompt_requires_structured_subject_detail(self):
        prompt = build_expert_prompt()

        self.assertIn("请不要生成图片", prompt)
        self.assertIn("最高规则", prompt)
        self.assertIn("必须只输出图中直接看见的事实", prompt)
        self.assertIn("不得猜想", prompt)
        self.assertIn("禁止使用猜测词", prompt)
        self.assertIn("看不见的属性直接省略", prompt)
        self.assertIn("“结构化视觉规格书”", prompt)
        self.assertIn("“最终提示词”", prompt)
        self.assertIn("模板污染禁止规则", prompt)
        self.assertIn("JSON值必须全部来自当前图片的可见观察", prompt)
        self.assertNotIn('"负面约束"', prompt)
        self.assertNotIn("negative_prompt", prompt)
        self.assertIn("所见清单、整体描述、背景、前景、空间关系、主体、姿态表情、服装材质、色彩光线风格、暴露与情色内容、细节", prompt)
        self.assertIn("先看后写工作流", prompt)
        self.assertIn("Step 1 观察阶段", prompt)
        self.assertIn("Step 2 分析阶段", prompt)
        self.assertIn("Step 3 撰写阶段", prompt)
        self.assertIn("Step 4 自检阶段", prompt)
        self.assertIn("逐项扫描清单", prompt)
        self.assertIn("统一视觉规格书规则", prompt)
        self.assertIn("姿态复刻锁定规则", prompt)
        self.assertIn("身体轴线从画面哪个区域延伸到哪个区域", prompt)
        self.assertIn("关键负空间", prompt)
        self.assertIn("重复偏差防滑规则", prompt)
        self.assertIn("最终提示词没有对应句子", prompt)
        self.assertIn("加强模式详细度要求", prompt)
        self.assertIn("细节数组至少输出五条完整长句", prompt)
        self.assertIn("最终提示词必须整合结构化视觉规格书中的主要事实", prompt)
        self.assertIn("主体人物", prompt)
        self.assertIn("红色易拉罐", prompt)
        self.assertIn("灰色金属墙面", prompt)
        self.assertIn("不得输出角色1", prompt)
        self.assertIn("物体用具体可见名称", prompt)
        self.assertIn("整体描述只写最抽象的画面类型和主旨", prompt)
        self.assertIn("结构化描述顺序必须先整体描述，再背景，再前景，再主体，最后细节", prompt)
        self.assertNotIn('"主体1"', prompt)
        self.assertNotIn('"物体1"', prompt)
        self.assertNotIn("构图镜头：", prompt)
        self.assertNotIn("人物姿态：", prompt)
        self.assertNotIn("服装材质：", prompt)
        self.assertNotIn("光线颜色风格：", prompt)
        self.assertNotIn('"关键保留点"', prompt)
        self.assertNotIn('"不确定项"', prompt)
        self.assertIn("不要输出任何带下划线的内部字段名", prompt)
        self.assertIn("字段名、章节名、编号", prompt)
        self.assertIn("关键保留点、易错点、禁止项和不确定项不得写入最终提示词或结构化视觉规格书", prompt)
        self.assertIn("所有字段都是候选字段", prompt)
        self.assertIn("没有可见事实的字段必须整项省略", prompt)
        self.assertIn("不要输出空字符串", prompt)
        self.assertIn("禁止依赖后期清洗", prompt)
        self.assertIn("量化规则", prompt)
        self.assertIn("画面比例与主体占比规则", prompt)
        self.assertIn("近似宽高比", prompt)
        self.assertIn("主体外接框占整个画面的比例", prompt)
        self.assertIn("主体占画面宽度和高度比例", prompt)
        self.assertIn("年龄倾向", prompt)
        self.assertIn("可见族裔/人种外貌倾向", prompt)
        self.assertIn("肤色", prompt)
        self.assertIn("表情与表情依据", prompt)
        self.assertIn("暴露到什么程度", prompt)
        self.assertIn("暴露与情色内容规则", prompt)
        self.assertIn("成人裸露", prompt)
        self.assertIn("可见证据门槛", prompt)
        self.assertIn("从人体结构和肢体解剖学角度自适应分析", prompt)
        self.assertIn("不要使用固定清单式输出", prompt)
        self.assertIn("禁止把臀部曲线、大腿根、腹股沟、衣物阴影或低清晰度区域推断成外生殖器", prompt)
        self.assertIn("动作、躯干扭转、关节链、腿部开合、手部接触、衣物边缘、遮挡关系和裁切边界", prompt)
        self.assertIn("胸部和下体暴露内容按可见证据自适应命名", prompt)
        self.assertIn("解剖层级不可继承", prompt)
        self.assertIn("可见大阴唇不等于可见小阴唇、阴蒂或阴道口", prompt)
        self.assertIn("外生殖器", prompt)
        self.assertIn("阴茎", prompt)
        self.assertIn("龟头", prompt)
        self.assertIn("外阴区域", prompt)
        self.assertIn("阴唇轮廓", prompt)
        self.assertIn("阴道口", prompt)
        self.assertIn("阴蒂", prompt)
        self.assertIn("外观美学描述标准", prompt)
        self.assertIn("解剖名词 + 外观形态 + 色彩肤色 + 毛发分布", prompt)
        self.assertIn("大阴唇轮廓柔和贴合", prompt)
        self.assertIn("龟头偏粉", prompt)
        self.assertIn("无可见毛发、稀疏短毛、细软毛发", prompt)
        self.assertIn("乳房体积中等、轮廓圆润", prompt)
        self.assertIn("暴露与情色内容字段只允许说明可见暴露事实", prompt)
        self.assertIn("不得逐项声明某个解剖部位没有可见", prompt)
        self.assertIn("禁止写“无过度暴露、没有明显情色、未见性行为、未见性器官、不可见乳头/乳晕/外生殖器”等否定判断", prompt)
        self.assertIn("情色姿态", prompt)
        self.assertIn("性意味接触", prompt)
        self.assertIn("性意味接触", prompt)
        self.assertIn("衣物遮挡边界", prompt)
        self.assertIn("服装细节规则", prompt)
        self.assertIn("不能只写颜色、长短和材质", prompt)
        self.assertIn("版型", prompt)
        self.assertIn("缝线", prompt)
        self.assertIn("拼接线", prompt)
        self.assertIn("包边", prompt)
        self.assertIn("针织纹", prompt)
        self.assertIn("蕾丝花纹", prompt)
        self.assertIn("格纹走向", prompt)
        self.assertIn("衣物边缘覆盖关系", prompt)
        self.assertIn("躯干", prompt)
        self.assertIn("左", prompt)
        self.assertIn("右", prompt)
        self.assertIn("构图与镜头", prompt)
        self.assertIn("摄影设备", prompt)
        self.assertIn("拍摄角度", prompt)
        self.assertIn("机位高度", prompt)
        self.assertIn("焦距感", prompt)
        self.assertIn("透视畸变", prompt)
        self.assertIn("入射", prompt)
        self.assertNotIn("aa" + "、ab" + "、ac", prompt)
        self.assertNotIn("b" + "c", prompt)
        self.assertLess(len(prompt), 12000)

    def test_expert_team_prompts_are_separate_stages(self):
        global_prompt = build_expert_team_global_prompt()
        subject_prompt = build_expert_team_subject_prompt({"主体判定": "人物主体", "主体类型": "person"})
        review_prompt = build_expert_team_review_prompt({"主体细节": "人物主体细节"})
        combined_prompt = global_prompt + subject_prompt + review_prompt

        self.assertIn("专家第1轮", global_prompt)
        self.assertIn("专家第2轮", subject_prompt)
        self.assertIn("专家第3轮", review_prompt)
        self.assertIn("必须只输出图中直接看见的事实", combined_prompt)
        self.assertIn("不得猜想", combined_prompt)
        self.assertIn("禁止使用猜测词", combined_prompt)
        self.assertNotIn("专家团第", combined_prompt)
        self.assertIn("专家计划", global_prompt)
        self.assertIn("专家观点", subject_prompt)
        self.assertIn("复核", review_prompt)
        self.assertIn("量化规则", global_prompt)
        self.assertIn("画面比例与主体占比规则", combined_prompt)
        self.assertIn('"画面比例与主体占比"', subject_prompt)
        self.assertIn("字段名清单，不是内容模板", subject_prompt)
        self.assertIn("不允许出现字段要求本身", subject_prompt)
        self.assertIn("近似宽高比", combined_prompt)
        self.assertIn("主体外接框占整个画面的比例", combined_prompt)
        self.assertIn("主体占画面宽度和高度比例", combined_prompt)
        self.assertIn("至少包含两类量化信息", subject_prompt)
        self.assertIn("专家观点只能补充主体细节未覆盖的事实", subject_prompt)
        self.assertIn("整体描述", combined_prompt)
        self.assertIn("背景", subject_prompt)
        self.assertIn("前景", subject_prompt)
        self.assertIn("不得输出角色1", combined_prompt)
        self.assertIn("物体用具体可见名称", combined_prompt)
        self.assertNotIn("构图镜头：", combined_prompt)
        self.assertNotIn("人物姿态：", combined_prompt)
        self.assertNotIn("服装材质：", combined_prompt)
        self.assertNotIn("光线颜色风格：", combined_prompt)
        self.assertIn("摄影设备", combined_prompt)
        self.assertIn("拍摄角度", combined_prompt)
        self.assertIn("机位高度", combined_prompt)
        self.assertIn("焦距感", combined_prompt)
        self.assertIn("透视畸变", combined_prompt)
        self.assertIn("专家模式强制补齐三项", subject_prompt)
        self.assertIn("服装细节规则", subject_prompt)
        self.assertIn("版型长短", subject_prompt)
        self.assertIn("纹理", subject_prompt)
        self.assertIn("缝线", subject_prompt)
        self.assertIn('"人物外貌"', subject_prompt)
        self.assertIn('"关节角度"', subject_prompt)
        self.assertIn('"镜头倾斜角度"', subject_prompt)
        self.assertIn('"暴露与情色内容"', subject_prompt)
        self.assertIn("真实可见的暴露内容", subject_prompt)
        self.assertIn("乳头、乳晕、外阴区域", subject_prompt)
        self.assertIn("阴茎、龟头", subject_prompt)
        self.assertIn("外生殖器外观", subject_prompt)
        self.assertIn("禁止输出左侧点、右侧点、下体点", subject_prompt)
        self.assertIn("人体结构和肢体解剖学角度分析动作", subject_prompt)
        self.assertIn("禁止固定清单式列举", subject_prompt)
        self.assertIn("专家观点职责边界", subject_prompt)
        self.assertIn("完全不同的视觉领域", subject_prompt)
        self.assertIn("相辅相成而不是相互矛盾", subject_prompt)
        self.assertIn("头颈视线", subject_prompt)
        self.assertIn("躯干重心", subject_prompt)
        self.assertIn("四肢端点", subject_prompt)
        self.assertIn("禁止用一条姿态结构概括全部动作", subject_prompt)
        self.assertIn("必须检查是否分别存在头颈视线、躯干重心、四肢端点三条人体观点", review_prompt)
        self.assertIn("同一事实、同一物体、同一身体部位", subject_prompt)
        self.assertIn("如果两个专家都想写同一内容，只保留更专业、更细的那个维度", subject_prompt)
        self.assertIn("如果某维度只能写出其他专家已经覆盖的内容，必须省略该维度", subject_prompt)
        self.assertIn("文字、水印、Logo 只允许在文字标识维度", review_prompt)
        self.assertIn("暴露与情色内容只允许在暴露与情色内容维度", review_prompt)
        self.assertIn("检查是否遗漏服装类型、版型长短、颜色、材质、纹理", review_prompt)
        self.assertIn("动作、关节、腿部开合、手部接触、衣物边缘", review_prompt)
        self.assertIn("禁止用左侧点、右侧点、下体点代替具体解剖名称", review_prompt)
        self.assertIn("禁止固定清单式列举", review_prompt)
        self.assertIn("禁止把臀部曲线、大腿根、腹股沟、衣物阴影或低清晰度区域推断成外生殖器", review_prompt)
        self.assertIn("肢体左右参照规则", combined_prompt)
        self.assertIn("画面左侧肩肘腕", combined_prompt)
        self.assertIn("画面右侧髋膝踝", combined_prompt)
        self.assertIn("禁止单独使用“左手、右手", combined_prompt)
        self.assertIn("相机俯仰角", combined_prompt)
        self.assertIn("画面roll顺/逆时针倾斜角", combined_prompt)
        self.assertIn("年龄倾向", review_prompt)
        self.assertIn("肤色", review_prompt)
        self.assertIn("表情与表情依据", review_prompt)
        self.assertIn("暴露到什么程度", combined_prompt)
        self.assertIn("情色姿态", combined_prompt)
        self.assertIn("性意味接触", combined_prompt)
        self.assertIn("缺少则补充近似比例", review_prompt)
        self.assertNotIn('"负面约束"', combined_prompt)
        self.assertNotIn("negative_prompt", combined_prompt)
        self.assertIn("没有可见事实的字段必须整项省略", combined_prompt)
        self.assertIn("禁止依赖后期清洗", combined_prompt)
        self.assertNotIn("aa" + "、ab" + "、ac", combined_prompt)
        self.assertNotIn("b" + "c", combined_prompt)
        self.assertLess(len(global_prompt), 4800)
        self.assertLess(len(subject_prompt), 8200)
        self.assertLess(len(review_prompt), 8400)


if __name__ == "__main__":
    unittest.main()
