from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class StylePresetUiTests(unittest.TestCase):
    def test_style_catalog_uses_generic_block_plus_model_family_block(self):
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()

        self.assertIn("var STYLE_PROMPT_VERSION = 4", generate_js)
        self.assertIn("var STYLE_CATEGORIES = [", generate_js)
        self.assertIn("var STYLE_PRESETS = [", generate_js)
        self.assertIn("{ id: 'photography', label: '摄影/人像' }", generate_js)
        self.assertIn("{ id: 'film', label: '影像质感' }", generate_js)
        self.assertIn("{ id: 'game', label: '游戏制作' }", generate_js)
        self.assertIn("{ id: 'illustration', label: '插画/动漫' }", generate_js)
        self.assertIn("id: 'hyperrealistic'", generate_js)
        self.assertIn("category: 'photography'", generate_js)
        self.assertIn("label: '超写实'", generate_js)
        self.assertIn("id: 'anime'", generate_js)
        self.assertIn("id: 'premium_3d'", generate_js)
        self.assertIn("id: 'aaa_game_asset'", generate_js)
        self.assertIn("category: 'game'", generate_js)
        self.assertIn("id: 'pixel_game'", generate_js)
        self.assertIn("id: 'low_poly_game'", generate_js)
        self.assertIn("id: 'film_noir'", generate_js)
        self.assertIn("id: 'vintage_film'", generate_js)
        self.assertIn("final image must be AAA game character or prop asset concept art", generate_js)
        self.assertIn("final image must become pixel art game artwork", generate_js)
        self.assertIn("final image must become low-poly game art", generate_js)
        self.assertIn("final image must become a film noir still", generate_js)
        self.assertIn("do not convert the subject into a human", generate_js)
        self.assertNotIn("id: 'game_concept'", generate_js)
        self.assertNotIn("id: 'cinematic'", generate_js)
        self.assertIn("STYLE LOCK: final image must be rendered as finished anime character artwork", generate_js)
        self.assertIn("STYLE LOCK: final image must become a high-end 3D production render", generate_js)
        self.assertIn("var STYLE_FAMILY_BLOCKS = {", generate_js)
        self.assertIn("qwen: 'Qwen tuning:", generate_js)
        self.assertIn("flux2: 'FLUX.2 tuning:", generate_js)
        self.assertIn("z_image: 'Z-Image tuning:", generate_js)
        self.assertIn("ernie: 'ERNIE prompt-enhancer tuning / 画风锁定:", generate_js)
        self.assertIn("必须把用户提示词改写到所选画风中", generate_js)
        self.assertIn("不能替换为真人", generate_js)
        self.assertIn("style_lock: preset.lock || preset.generic || ''", generate_js)
        self.assertIn("general_style: preset.generic || ''", generate_js)
        self.assertIn("model_family_tuning: familyBlock", generate_js)

    def test_style_selector_renders_under_prompt_and_submits_metadata(self):
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()
        css = (ROOT / "static/css/style.css").read_text()

        self.assertIn("function _stylePresetControlHtml", generate_js)
        self.assertIn("function _stylePresetOptionsHtml(selectedId)", generate_js)
        self.assertIn("<optgroup label=", generate_js)
        self.assertIn("function _styleCategoryForPreset", generate_js)
        self.assertIn("function _bypassErniePromptEnhancerForStyle", generate_js)
        self.assertIn("targetFields.__style_prompt_enhancer_bypass = 'ernie_direct_style_lock'", generate_js)
        self.assertIn("_bypassErniePromptEnhancerForStyle(styleInfo, submitFieldsMeta, fields, snapshot)", generate_js)
        self.assertNotIn("id=\"styleCategorySelect\"", generate_js)
        self.assertIn("id=\"stylePresetSelect\"", generate_js)
        self.assertIn("画面风格增强", generate_js)
        self.assertIn("aria-label=\"画面风格增强\"", generate_js)
        self.assertIn("无风格增强", generate_js)
        self.assertNotIn("保留原提示词", generate_js)
        self.assertIn("styleControlHtml = _stylePresetControlHtml(fields)", generate_js)
        self.assertIn("<textarea id=\"promptInput\"", generate_js)
        self.assertIn("prompt-input-wrap prompt-input-wrap-with-style", generate_js)
        self.assertIn("\"></textarea>' + styleControlHtml + ideogramCanvasHtml + '</div><div class=\"prompt-actions\">", generate_js)
        self.assertIn("fields.__style_preset_id = styleInfo.id", generate_js)
        self.assertIn("fields.__style_model_family = styleInfo.family", generate_js)
        self.assertIn("fields.__style_prompt_version = styleInfo.version", generate_js)
        self.assertIn("fields.__style_prompt_text = styleInfo.prompt", generate_js)
        self.assertIn(".style-preset-fg", css)
        self.assertIn(".style-preset-row", css)
        self.assertIn(".prompt-input-wrap-with-style", css)
        self.assertIn(".style-preset-inline-label", css)
        self.assertIn("@media (max-width: 600px)", css)
        self.assertIn("var style = _stylePresetById(_currentStylePresetId());", generate_js)
        self.assertIn("style.label + '｜' + prompt.trim()", generate_js)

    def test_style_prompt_composes_before_qwen_angle_and_restores_clean_user_prompt(self):
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()

        self.assertIn("function _stripExistingStylePromptBlocks", generate_js)
        self.assertIn("function _parsePromptJsonObject", generate_js)
        self.assertIn("function _promptJsonForStyle", generate_js)
        self.assertIn("function _preparePromptForCurrentControls", generate_js)
        self.assertIn("return _preparePromptForCurrentStyle(_preparePromptForCurrentQwenAngle(prompt));", generate_js)
        self.assertIn("var out = userJson ? Object.assign({}, userJson) : { prompt: base };", generate_js)
        self.assertIn("out.style = Object.assign({}, existingStyle, styleInfo.promptJson);", generate_js)
        self.assertIn("function _isIdeogram4Workflow", generate_js)
        self.assertIn("/ideogram/i.test(wf)", generate_js)
        self.assertIn("const styledPrompt = _isOfficialIdeogram4Workflow(submitFieldsMeta)", generate_js)
        self.assertIn("? _composeIdeogramCanvasPrompt(rawPrompt, styleInfo)", generate_js)
        self.assertIn(": _promptWithStylePreset(rawPrompt, styleInfo);", generate_js)
        self.assertIn("const prompt = _promptWithQwenAngle(styledPrompt, fields);", generate_js)
        self.assertIn("if (key === '__style_preset_id')", generate_js)
        self.assertIn("if (/^__style_/.test(String(key || '')))", generate_js)
        self.assertIn("if (key.indexOf('__') === 0) continue;", generate_js)

    def test_ideogram4_layout_canvas_renders_and_submits_json_caption(self):
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()
        css = (ROOT / "static/css/style.css").read_text()

        self.assertIn("var _ideogramCanvasState", generate_js)
        self.assertIn("function _ideogramCanvasControlHtml", generate_js)
        self.assertIn("data-ideogram-canvas-root", generate_js)
        self.assertIn("布局画布", generate_js)
        self.assertIn("data-ideogram-tool=\"rect\"", generate_js)
        self.assertIn("data-ideogram-tool=\"circle\"", generate_js)
        self.assertIn("function _composeIdeogramCanvasPrompt", generate_js)
        self.assertIn("function _ideogramCanvasSceneInstruction", generate_js)
        self.assertIn("function _ideogramCanvasPositionHint", generate_js)
        self.assertIn("function _ideogramCanvasSpatialSentence", generate_js)
        self.assertIn("function _ideogramCanvasWantsLayout", generate_js)
        self.assertIn("function _ideogramCanvasUseHardBbox", generate_js)
        self.assertIn("function _ideogramCanvasPhotoElements", generate_js)
        self.assertIn("function _ideogramCanvasSceneNote", generate_js)
        self.assertIn("function _ideogramCanvasNaturalPlacement", generate_js)
        self.assertIn("return _ideogramCanvasWantsLayout(base);", generate_js)
        self.assertIn("Coherent realistic photograph with naturally positioned elements", generate_js)
        self.assertIn("official Ideogram4 coordinate metadata", generate_js)
        self.assertIn("Fuse all object modules into one shared scene", generate_js)
        self.assertIn("keep text modules as precisely positioned typography only", generate_js)
        self.assertIn("var objectNotes = [];", generate_js)
        self.assertIn("objectNotes.push(_ideogramCanvasSceneNote(shape, text));", generate_js)
        self.assertIn("One uninterrupted photographic scene that fuses all object modules", generate_js)
        self.assertIn("not a grid", generate_js)
        self.assertIn("Render the literal text", generate_js)
        self.assertIn("only the letter strokes should be visible", generate_js)
        self.assertIn("Do not draw any rectangle, outline, border, textbox", generate_js)
        self.assertIn("Subject details:", generate_js)
        self.assertIn("Describe it with concrete visual detail", generate_js)
        self.assertIn("no collage", generate_js)
        self.assertIn("white card", generate_js)
        self.assertIn("no split-screen", generate_js)
        self.assertIn("diptych", generate_js)
        self.assertIn("vertical divider", generate_js)
        self.assertIn("PPT-style separated region", generate_js)
        self.assertIn("? shapes.map(function(shape)", generate_js)
        self.assertIn(": _ideogramCanvasPhotoElements(shapes)", generate_js)
        self.assertIn("bbox: _ideogramCanvasBbox(shape)", generate_js)
        self.assertIn("type: 'text'", generate_js)
        self.assertIn("_ideogramCanvasElementDesc(shape, text)", generate_js)
        self.assertIn("_ideogramCanvasTextDesc(shape)", generate_js)
        self.assertIn("fields.__ideogram4_canvas = JSON.stringify(_ideogramCanvasExportPayload())", generate_js)
        self.assertIn("return _restoreIdeogramCanvasFromFieldValue(value);", generate_js)
        self.assertIn(".ideogram-canvas-stage", css)
        self.assertIn(".ideogram-shape-circle", css)
        self.assertIn(".ideogram-shape-resize", css)

    def test_style_family_detection_covers_current_model_families(self):
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()

        self.assertIn("function _styleFamilyForWorkflow", generate_js)
        self.assertIn("return 'ernie'", generate_js)
        self.assertIn("return 'z_image'", generate_js)
        self.assertIn("return 'qwen'", generate_js)
        self.assertIn("return 'flux2'", generate_js)
        self.assertIn("return 'generic'", generate_js)
        self.assertIn("/z[-_ ]?image|z[-_ ]?xxx|nunchaku/i", generate_js)
        self.assertIn("/qwen|千问/i", generate_js)


if __name__ == "__main__":
    unittest.main()
