from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class PromptInterrogateUiContractTests(unittest.TestCase):
    def test_interrogate_runs_in_background_and_result_requires_copy(self):
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()
        ui_js = (ROOT / "static/js/modules/ui.js").read_text()

        self.assertIn("function _startPromptInterrogateTask", generate_js)
        self.assertIn("CW.showPromptResultToast(prompt", generate_js)
        self.assertIn("CW.closePromptInterrogateModal", generate_js)
        self.assertIn("CW.showPromptInterrogatePendingToast", generate_js)
        self.assertIn('class="v4-overlay prompt-interrogate-modal"', generate_js)
        self.assertIn("requestAnimationFrame(function()", generate_js)
        self.assertIn("modal.classList.add('open')", generate_js)
        self.assertIn("modal.classList.remove('open')", generate_js)
        self.assertIn("window.CW.showPromptResultToast", ui_js)
        self.assertIn("window.CW.showPromptInterrogatePendingToast", ui_js)
        self.assertIn("window.CW.clearPromptInterrogateToast", ui_js)
        self.assertIn("function clearPromptInterrogateToast", ui_js)
        self.assertIn("CW.clearPromptInterrogateToast", generate_js)
        self.assertIn("图片反推中", ui_js)
        self.assertIn("反推完成", ui_js)
        self.assertNotIn("后台努力反推中，请稍后", ui_js)
        self.assertNotIn("顺利完成反推任务，点击查看", ui_js)
        self.assertNotIn("已复制到输入框", ui_js)
        self.assertIn("has-prompt-result-active", ui_js)
        self.assertIn("prompt-result-toast", ui_js)
        self.assertIn('data-action="view">点击查看', ui_js)
        self.assertIn("prompt-result-language", ui_js)
        self.assertIn("structured_prompt_json", ui_js)
        self.assertIn("structured_prompt_json_en", ui_js)
        self.assertIn("prompt-result-format", ui_js)
        self.assertIn('data-format="text"', ui_js)
        self.assertIn('data-format="json"', ui_js)
        self.assertIn("function setFormat", ui_js)
        self.assertIn("function getStructuredText", ui_js)
        self.assertIn("function canShowLanguage", ui_js)
        self.assertIn("纯词汇", ui_js)
        self.assertIn("JSON格式", ui_js)
        self.assertIn("prompt_zh", ui_js)
        self.assertIn("function _cleanPromptResultChinese", ui_js)
        self.assertIn("function _dropEnglishPromptFragments", ui_js)
        self.assertIn("A-Za-z0-9'’._+/-", ui_js)
        self.assertIn("Original(?:\\s+prompt)?", ui_js)
        self.assertIn("prompt-tool-label", generate_js)
        self.assertIn("图片反推</span>", generate_js)
        self.assertIn("function _isVideoPromptWorkflow", generate_js)
        self.assertIn("function _promptOptimizeCopy", generate_js)
        self.assertIn("视频脚本优化", generate_js)
        self.assertIn("data-optimize-mode", generate_js)
        self.assertIn("mode: copy.mode", generate_js)
        self.assertIn("function _videoScriptTimingContext", generate_js)
        self.assertIn("prompt_context: copy.mode === 'video_script' ? _videoScriptTimingContext() : {}", generate_js)
        self.assertIn("max_new_tokens: copy.mode === 'video_script' ? 768 : 384", generate_js)
        self.assertNotIn("用图片反推", generate_js)
        self.assertIn("translatePromptLanguage", generate_js)
        self.assertIn("/api/prompt/translate", generate_js)
        self.assertIn("PROMPT_TRANSLATION_CACHE_KEY", generate_js)
        self.assertIn("sessionStorage", generate_js)
        self.assertIn("_rememberPromptTranslationPair", generate_js)
        self.assertIn("registerPromptTranslationPair", generate_js)
        self.assertNotIn("max_new_tokens: 256", generate_js)
        self.assertNotIn("max_new_tokens: _translationTokenBudget(raw)", generate_js)
        self.assertIn("已快速切换为英文提示词", generate_js)
        self.assertIn("translatePromptBtn", generate_js)
        self.assertIn("中英切换", generate_js)
        self.assertIn("prompt-tool-btn-clear clear-btn", generate_js)
        self.assertIn("is-compact-disabled", generate_js)
        self.assertIn("disabled", generate_js)
        self.assertIn('aria-label="乘以">×</span>', generate_js)
        self.assertNotIn('sep-dim">x</span>', generate_js)
        self.assertIn("'×' + p[1]", generate_js)
        self.assertIn("trash-2", generate_js)
        self.assertIn("translateBtn.disabled = !hasText", ui_js)
        self.assertIn("clearBtn.disabled = !hasText", ui_js)
        self.assertIn("optimizeBtn.disabled = !hasText", ui_js)
        self.assertIn("复制到输入框", ui_js)
        self.assertIn("is-copy hidden", ui_js)
        self.assertIn("closePromptResultToast", ui_js)
        self.assertIn("viewBtn.classList.add('hidden')", ui_js)
        self.assertNotIn("当前显示：", ui_js)

    def test_prompt_action_layout_contract(self):
        css = (ROOT / "static/css/style.css").read_text()

        self.assertIn(".toast.is-persistent", css)
        self.assertIn("top: calc(var(--titlebar-h) + 40px)", css)
        self.assertIn("--toast-accent-rgb", css)
        self.assertIn("--toast-bg", css)
        self.assertIn("background: var(--toast-bg)", css)
        self.assertIn("border-radius: 999px", css)
        self.assertIn(".toast::before", css)
        self.assertIn("display: none", css)
        self.assertIn(".prompt-result-toast", css)
        self.assertIn(".prompt-result-pending .toast-icon svg", css)
        self.assertIn(".toast-container.has-prompt-result-expanded", css)
        self.assertIn(".toast-container.has-prompt-result-active", css)
        self.assertIn("top: 96px", css)
        self.assertIn("width: 50vw", css)
        self.assertIn("width: min(96vw, 920px)", css)
        self.assertIn("max-height: min(62vh, 520px)", css)
        self.assertIn(".toast-container.has-prompt-result-expanded .prompt-result-toast.is-expanded", css)
        self.assertIn(".prompt-result-toast.is-expanded", css)
        self.assertIn("border-radius: 14px", css)
        self.assertIn(".prompt-result-controls", css)
        self.assertIn("padding-bottom: 10px", css)
        self.assertIn(".prompt-result-control-left", css)
        self.assertIn(".prompt-result-language", css)
        self.assertIn(".prompt-result-format", css)
        self.assertIn(".prompt-result-format-btn.active", css)
        self.assertIn(".prompt-result-copy-row", css)
        self.assertIn(".prompt-tool-btn-vibrant .prompt-tool-label", css)
        self.assertIn(".prompt-input-wrap #promptInput", css)
        self.assertIn("min-height: 168px", css)
        self.assertIn(".gen-footer #btnGenerate", css)
        self.assertIn("min-height: 48px", css)
        self.assertIn("--prompt-tool-color: var(--accent)", css)
        self.assertIn("--prompt-tool-color: #22d3ee", css)
        self.assertIn(".prompt-tool-btn-translate", css)
        self.assertIn("--prompt-tool-color: #a78bfa", css)
        self.assertIn(".prompt-tool-btn-translate:hover:not(:disabled)", css)
        self.assertIn("color: currentColor", css)
        self.assertIn(".prompt-tool-btn-clear", css)
        self.assertIn("--prompt-tool-color: #f87171", css)
        self.assertIn(".prompt-actions #optimizePromptBtn", css)
        self.assertIn("transition:", css)
        self.assertIn("max-width .22s cubic-bezier(.2,.78,.2,1)", css)
        self.assertIn(".prompt-tool-btn .prompt-tool-label", css)
        self.assertIn(".prompt-tool-btn.is-compact-disabled", css)
        self.assertIn("font-size: 0", css)
        self.assertIn("line-height: 0", css)
        self.assertIn("background-image: none !important", css)
        self.assertIn(".prompt-tool-btn.is-compact-disabled .prompt-tool-label", css)
        self.assertIn("display: none", css)
        self.assertIn("#optimizePromptBtn.is-compact-disabled .cw-icon", css)
        self.assertIn("transform: translateX(1px)", css)
        self.assertIn("animation: none !important", css)
        self.assertIn("@media (max-width: 600px)", css)
        self.assertIn("flex-wrap: nowrap", css)
        self.assertIn(".prompt-actions #optimizePromptBtn", css)
        self.assertIn("margin-left: auto", css)
        self.assertIn("flex: 0 0 auto", css)
        self.assertIn("width: 13px", css)
        self.assertIn("height: 13px", css)
        self.assertIn("width: auto", css)
        self.assertIn(".prompt-actions .prompt-tool-btn.is-compact-disabled .prompt-tool-label", css)
        self.assertIn("display: inline-block", css)
        self.assertIn(".prompt-actions:not(.has-content)", css)
        self.assertIn("width: 100%", css)
        self.assertIn("#optimizePromptBtn.is-compact-disabled", css)
        self.assertIn(".prompt-tool-btn:not(.prompt-tool-btn-vibrant):hover:not(:disabled)", css)
        self.assertIn("@keyframes promptToolBorderCycle", css)
        self.assertIn("repeating-linear-gradient(100deg", css)
        self.assertIn("background-origin: padding-box, border-box", css)
        self.assertIn("background-clip: padding-box, border-box", css)
        self.assertIn("220px 50%", css)
        self.assertNotIn("240% 50%", css)
        self.assertNotIn("promptToolShine", css)
        self.assertNotIn("promptToolTextCycle", css)
        self.assertNotIn("linear-gradient(135deg, rgba(17,35,68,.98)", css)
        self.assertIn(".prompt-interrogate-actions .prompt-tool-btn", css)
        self.assertIn(".prompt-interrogate-modal .prompt-interrogate-upload", css)
        self.assertIn(".prompt-interrogate-modal.open .prompt-interrogate-upload", css)
        self.assertIn("transform: translateY(10px)", css)
        self.assertIn("transition-delay: 60ms", css)
        self.assertIn("margin-left: auto", css)


if __name__ == "__main__":
    unittest.main()
