from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class PromptInterrogateUiContractTests(unittest.TestCase):
    def test_interrogate_runs_in_background_and_result_requires_copy(self):
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()
        ui_js = (ROOT / "static/js/modules/ui.js").read_text()

        self.assertIn("function _startPromptInterrogateTask", generate_js)
        self.assertIn("CW.showPromptResultToast(prompt", generate_js)
        self.assertIn("CW.closePromptInterrogateModal", generate_js)
        self.assertIn("CW.showPromptInterrogatePendingToast", generate_js)
        self.assertIn('class="v4-overlay prompt-interrogate-modal"', generate_js)
        self.assertIn("requestAnimationFrame(function()", generate_js)
        self.assertIn("modal.classList.add('open')", generate_js)
        self.assertIn("modal.classList.remove('open')", generate_js)
        self.assertIn("window.CW.showPromptResultToast", ui_js)
        self.assertIn("window.CW.showPromptInterrogatePendingToast", ui_js)
        self.assertIn("window.CW.clearPromptInterrogateToast", ui_js)
        self.assertIn("function clearPromptInterrogateToast", ui_js)
        self.assertIn("CW.clearPromptInterrogateToast", generate_js)
        self.assertIn("图片反推中", ui_js)
        self.assertIn("反推完成", ui_js)
        self.assertNotIn("后台努力反推中，请稍后", ui_js)
        self.assertNotIn("顺利完成反推任务，点击查看", ui_js)
        self.assertNotIn("已复制到输入框", ui_js)
        self.assertIn("has-prompt-result-active", ui_js)
        self.assertIn("prompt-result-toast", ui_js)
        self.assertIn('data-action="view">点击查看', ui_js)
        self.assertIn("prompt-result-language", ui_js)
        self.assertIn("structured_prompt_json", ui_js)
        self.assertIn("structured_prompt_json_en", ui_js)
        self.assertNotIn("prompt-result-negative", ui_js)
        self.assertIn("data.structured_optimized_prompt || data.prompt", generate_js)
        self.assertIn("prompt-result-format", ui_js)
        self.assertNotIn("model_comparison", ui_js)
        self.assertNotIn("模型横向对照", ui_js)
        self.assertNotIn("Qwen 独有", ui_js)
        self.assertIn('data-format="text"', ui_js)
        self.assertIn('data-format="json"', ui_js)
        self.assertIn("function setFormat", ui_js)
        self.assertIn("function getStructuredText", ui_js)
        self.assertIn("function canShowLanguage", ui_js)
        self.assertIn("纯词汇", ui_js)
        self.assertIn("JSON格式", ui_js)
        self.assertIn("prompt_zh", ui_js)
        self.assertIn("function _cleanPromptResultChinese", ui_js)
        self.assertIn("function _dropEnglishPromptFragments", ui_js)
        self.assertIn("A-Za-z0-9'’._+/-", ui_js)
        self.assertIn("Original(?:\\s+prompt)?", ui_js)
        self.assertIn("prompt-tool-label", generate_js)
        self.assertIn("图片反推</span>", generate_js)
        self.assertNotIn("promptInterrogateCompareRunBtn", generate_js)
        self.assertNotIn("compare_models", generate_js)
        self.assertNotIn("模型对照", generate_js)
        self.assertIn("function _isVideoPromptWorkflow", generate_js)
        self.assertIn("function _promptOptimizeCopy", generate_js)
        self.assertIn("视频脚本优化", generate_js)
        self.assertIn("data-optimize-mode", generate_js)
        self.assertIn("mode: copy.mode", generate_js)
        self.assertIn("function _videoScriptTimingContext", generate_js)
        self.assertIn("prompt_context: (level === 0 && copy.mode === 'video_script') ? _videoScriptTimingContext() : {}", generate_js)
        self.assertIn("node_title: f.node_title", generate_js)
        self.assertIn("function _timingKindForField", generate_js)
        self.assertIn("body: JSON.stringify(_promptInterrogatePayload(refVal, options || {}))", generate_js)
        self.assertIn("level: level", generate_js)
        self.assertIn("expert: level > 0", generate_js)
        self.assertIn("expert_team: level >= 2", generate_js)
        self.assertIn("mode: level > 0 ? 'image' : copy.mode", generate_js)
        self.assertIn("mode: copy.mode", generate_js)
        self.assertIn("promptInterrogateExpertRunBtn", generate_js)
        self.assertIn("promptInterrogateTeamRunBtn", generate_js)
        self.assertIn(" 标准", generate_js)
        self.assertIn(" 高级", generate_js)
        self.assertIn(" 专家", generate_js)
        self.assertNotIn("专家团反推", generate_js)
        self.assertIn("_startPromptInterrogateTask(uploadedName, { level: 1 })", generate_js)
        self.assertIn("_startPromptInterrogateTask(uploadedName, { level: 2 })", generate_js)
        self.assertIn("CW.icon('zap') : '') + ' 高级", generate_js)
        self.assertIn("CW.icon('users') : '') + ' 专家", generate_js)
        self.assertIn("function rerunPromptInterrogateFromResult", generate_js)
        self.assertIn("window.CW.rerunPromptInterrogateFromResult = rerunPromptInterrogateFromResult", generate_js)
        self.assertIn("_startPromptInterrogateTask(refVal, { level: nextLevel })", generate_js)
        self.assertNotIn("CW.icon('sparkles')", generate_js)
        self.assertIn("max_new_tokens: copy.mode === 'video_script' ? 768 : 384", generate_js)
        self.assertNotIn("用图片反推", generate_js)
        self.assertIn("translatePromptLanguage", generate_js)
        self.assertIn("/api/prompt/translate", generate_js)
        self.assertIn("PROMPT_TRANSLATION_CACHE_KEY", generate_js)
        self.assertNotIn('data-action="expert"', ui_js)
        self.assertIn("function renderExpertPanel", ui_js)
        self.assertIn("评审专家", ui_js)
        self.assertIn("断言准确率", ui_js)
        self.assertIn("claim_checks", ui_js)
        self.assertIn("review_retry_count", ui_js)
        self.assertNotIn("function applyExpertResult", ui_js)
        self.assertNotIn("CW.runPromptExpertInterrogate", ui_js)
        self.assertIn("高级反推", ui_js)
        self.assertIn("专家反推", ui_js)
        self.assertNotIn("专家团反推", ui_js)
        self.assertIn("prompt-result-level", ui_js)
        self.assertIn("prompt-result-level-btn", ui_js)
        self.assertIn("用当前图片切换反推级别重新生成", ui_js)
        self.assertIn("data-level", ui_js)
        self.assertIn("CW.rerunPromptInterrogateFromResult(sourceImage, nextLevel)", ui_js)
        self.assertIn("source_image", ui_js)
        self.assertIn("interrogate_elapsed_seconds", ui_js)
        self.assertIn("耗时 ", ui_js)
        self.assertIn("sessionStorage", generate_js)
        self.assertIn("_rememberPromptTranslationPair", generate_js)
        self.assertIn("registerPromptTranslationPair", generate_js)
        self.assertNotIn("max_new_tokens: 256", generate_js)
        self.assertNotIn("max_new_tokens: _translationTokenBudget(raw)", generate_js)
        self.assertIn("已快速切换为英文提示词", generate_js)
        self.assertIn("translatePromptBtn", generate_js)
        self.assertIn("中英切换", generate_js)
        self.assertIn("prompt-tool-btn-clear clear-btn", generate_js)
        self.assertIn("is-compact-disabled", generate_js)
        self.assertIn("disabled", generate_js)
        self.assertIn('aria-label="乘以">×</span>', generate_js)
        self.assertNotIn('sep-dim">x</span>', generate_js)
        self.assertIn("'×' + p[1]", generate_js)
        self.assertIn("trash-2", generate_js)
        self.assertIn("translateBtn.disabled = !hasText", ui_js)
        self.assertIn("clearBtn.disabled = !hasText", ui_js)
        self.assertIn("optimizeBtn.disabled = !hasText", ui_js)
        self.assertIn("复制到输入框", ui_js)
        self.assertIn("复刻正向提示词", ui_js)
        self.assertNotIn("复刻完整提示词", ui_js)
        self.assertNotIn("复刻负面提示词", ui_js)
        self.assertNotIn('data-action="replicate-full"', ui_js)
        self.assertIn('data-action="replicate-positive"', ui_js)
        self.assertNotIn('data-action="replicate-negative"', ui_js)
        self.assertNotIn("function expertFullPromptText", ui_js)
        self.assertIn("function expertPositivePromptText", ui_js)
        self.assertNotIn("function expertNegativePromptText", ui_js)
        self.assertIn("function replicateExpertPrompt", ui_js)
        self.assertIn("function setPromptControlValue", ui_js)
        self.assertIn("没有可复刻的提示词", ui_js)
        self.assertNotIn("function copyTextToClipboard", ui_js)
        self.assertNotIn("复制完整提示词", ui_js)
        self.assertNotIn("复制正向提示词", ui_js)
        self.assertNotIn("复制负面提示词", ui_js)
        self.assertIn("function buildExpertFallbackStructuredJson", ui_js)
        self.assertIn("if (!structuredJson && expertData) structuredJson = buildExpertFallbackStructuredJson()", ui_js)
        self.assertNotIn("专家负面", ui_js)
        self.assertIn("is-copy hidden", ui_js)
        self.assertIn("closePromptResultToast", ui_js)
        self.assertIn("viewBtn.classList.add('hidden')", ui_js)
        self.assertNotIn("当前显示：", ui_js)

    def test_prompt_action_layout_contract(self):
        css = (ROOT / "static/css/style.css").read_text()

        self.assertIn(".toast.is-persistent", css)
        self.assertIn("top: calc(var(--titlebar-h) + 40px)", css)
        self.assertIn("--toast-accent-rgb", css)
        self.assertIn("--toast-bg", css)
        self.assertIn("background: var(--toast-bg)", css)
        self.assertIn("border-radius: 999px", css)
        self.assertIn(".toast::before", css)
        self.assertIn("display: none", css)
        self.assertIn(".prompt-result-toast", css)
        self.assertIn(".prompt-result-pending .toast-icon svg", css)
        self.assertIn(".toast-container.has-prompt-result-expanded", css)
        self.assertIn(".toast-container.has-prompt-result-active", css)
        self.assertIn("top: 96px", css)
        self.assertIn("width: 50vw", css)
        self.assertIn("width: min(96vw, 920px)", css)
        self.assertIn('data-action="view"]', css)
        self.assertIn("linear-gradient(180deg, #fbbf24, #f59e0b)", css)
        self.assertIn("max-height: min(34vh, 220px)", css)
        self.assertIn("max-height: calc(100dvh - 176px)", css)
        self.assertIn("overflow-y: auto", css)
        self.assertIn("overscroll-behavior: contain", css)
        self.assertIn("scrollbar-gutter: stable", css)
        self.assertIn(".toast-container.has-prompt-result-expanded .prompt-result-toast.is-expanded", css)
        self.assertIn(".prompt-result-toast.is-expanded", css)
        self.assertIn("border-radius: 14px", css)
        self.assertIn(".prompt-result-controls", css)
        self.assertIn("grid-template-columns: minmax(0, 1fr)", css)
        self.assertIn("padding-bottom: 10px", css)
        self.assertIn(".prompt-result-control-left", css)
        self.assertIn("justify-content: space-between", css)
        self.assertIn("flex-wrap: nowrap", css)
        self.assertIn(".prompt-result-language", css)
        self.assertIn(".prompt-result-format", css)
        self.assertIn(".prompt-result-level", css)
        self.assertIn(".prompt-result-level-btn", css)
        self.assertIn("white-space: nowrap", css)
        self.assertIn(".prompt-result-format-btn.active", css)
        self.assertIn(".prompt-result-level-btn.active", css)
        self.assertIn(".prompt-result-copy-row", css)
        self.assertIn("flex-wrap: wrap", css)
        self.assertIn("flex-direction: column", css)
        self.assertIn(".prompt-result-expert-panel", css)
        self.assertIn(".prompt-interrogate-team-btn", css)
        self.assertIn(".prompt-result-expert-review", css)
        self.assertIn(".prompt-result-expert-review-detail", css)
        self.assertIn(".prompt-result-expert-list", css)
        self.assertIn(".prompt-result-expert-item", css)
        self.assertNotIn(".prompt-result-compare-stage", css)
        self.assertIn("width: 100%", css)
        self.assertIn("min-height: 36px", css)
        self.assertIn(".prompt-tool-btn-vibrant .prompt-tool-label", css)
        self.assertIn(".prompt-input-wrap #promptInput", css)
        self.assertIn("min-height: 168px", css)
        self.assertIn(".gen-footer #btnGenerate", css)
        self.assertIn("min-height: 48px", css)
        self.assertIn("--prompt-tool-color: var(--accent)", css)
        self.assertIn("--prompt-tool-color: #22d3ee", css)
        self.assertIn(".prompt-tool-btn-translate", css)
        self.assertIn("--prompt-tool-color: #a78bfa", css)
        self.assertIn(".prompt-tool-btn-translate:hover:not(:disabled)", css)
        self.assertIn("0 0 18px rgba(var(--prompt-tool-rgb), .32)", css)
        self.assertIn("filter: brightness(1.08)", css)
        self.assertIn(".prompt-variant-panel", css)
        self.assertIn("border: 0", css)
        self.assertIn("background: transparent", css)
        self.assertIn("box-shadow: none", css)
        self.assertIn("color: currentColor", css)
        self.assertIn(".prompt-tool-btn-clear", css)
        self.assertIn("--prompt-tool-color: #f87171", css)
        self.assertIn(".prompt-actions #optimizePromptBtn", css)
        self.assertIn("transition:", css)
        self.assertIn("max-width .22s cubic-bezier(.2,.78,.2,1)", css)
        self.assertIn(".prompt-tool-btn .prompt-tool-label", css)
        self.assertIn(".prompt-tool-btn.is-compact-disabled", css)
        self.assertIn("font-size: 0", css)
        self.assertIn("line-height: 0", css)
        self.assertIn("background-image: none !important", css)
        self.assertIn(".prompt-tool-btn.is-compact-disabled .prompt-tool-label", css)
        self.assertIn("display: none", css)
        self.assertIn("#optimizePromptBtn.is-compact-disabled .cw-icon", css)
        self.assertIn("transform: translateX(1px)", css)
        self.assertIn("animation: none !important", css)
        self.assertIn("@media (max-width: 600px)", css)
        self.assertIn("flex-wrap: nowrap", css)
        self.assertIn(".prompt-actions #optimizePromptBtn", css)
        self.assertIn("margin-left: auto", css)

        self.assertIn("flex: 0 0 auto", css)
        self.assertIn("width: 13px", css)
        self.assertIn("height: 13px", css)
        self.assertIn("width: auto", css)
        self.assertIn(".prompt-actions .prompt-tool-btn.is-compact-disabled .prompt-tool-label", css)
        self.assertIn("display: inline-block", css)
        self.assertIn(".prompt-actions:not(.has-content)", css)
        self.assertIn("width: 100%", css)
        self.assertIn("#optimizePromptBtn.is-compact-disabled", css)
        self.assertIn(".prompt-tool-btn:not(.prompt-tool-btn-vibrant):hover:not(:disabled)", css)
        self.assertIn("@keyframes promptToolBorderCycle", css)
        self.assertIn("repeating-linear-gradient(100deg", css)
        self.assertIn("background-origin: padding-box, border-box", css)
        self.assertIn("background-clip: padding-box, border-box", css)
        self.assertIn("220px 50%", css)
        self.assertNotIn("240% 50%", css)
        self.assertNotIn("promptToolShine", css)
        self.assertNotIn("promptToolTextCycle", css)
        self.assertNotIn("linear-gradient(135deg, rgba(17,35,68,.98)", css)
        self.assertIn(".prompt-interrogate-actions .prompt-tool-btn", css)
        self.assertIn(".prompt-interrogate-modal .prompt-interrogate-upload", css)
        self.assertIn(".prompt-interrogate-modal.open .prompt-interrogate-upload", css)
        self.assertIn("transform: translateY(10px)", css)
        self.assertIn("transition-delay: 60ms", css)
        self.assertIn("margin-left: auto", css)

    def test_generate_button_label_uses_start_generation(self):
        index_html = (ROOT / "static/index.html").read_text()
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()

        self.assertIn("> 开始生成</button>", index_html)
        self.assertIn("CW.icon('play') + ' 开始生成'", generate_js)
        self.assertNotIn('id="btnGenerate"><svg class="cw-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" ><use href="#icon-play"/></svg> 出图</button>', index_html)
        self.assertNotIn("CW.icon('play') + ' 出图'", generate_js)


if __name__ == "__main__":
    unittest.main()
