from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class PromptInterrogateUiContractTests(unittest.TestCase):
    def test_interrogate_runs_in_background_and_result_requires_copy(self):
        generate_js = (ROOT / "static/js/modules/generate.js").read_text()
        ui_js = (ROOT / "static/js/modules/ui.js").read_text()

        self.assertIn("function _startPromptInterrogateTask", generate_js)
        self.assertIn("CW.showPromptResultToast(prompt", generate_js)
        self.assertIn("CW.closePromptInterrogateModal", generate_js)
        self.assertIn("CW.showPromptInterrogatePendingToast", generate_js)
        self.assertIn('class="v4-overlay prompt-interrogate-modal"', generate_js)
        self.assertIn("requestAnimationFrame(function()", generate_js)
        self.assertIn("modal.classList.add('open')", generate_js)
        self.assertIn("modal.classList.remove('open')", generate_js)
        self.assertIn("window.CW.showPromptResultToast", ui_js)
        self.assertIn("window.CW.showPromptInterrogatePendingToast", ui_js)
        self.assertIn("图片反推中", ui_js)
        self.assertIn("反推完成", ui_js)
        self.assertNotIn("后台努力反推中，请稍后", ui_js)
        self.assertNotIn("顺利完成反推任务，点击查看", ui_js)
        self.assertNotIn("已复制到输入框", ui_js)
        self.assertIn("has-prompt-result-active", ui_js)
        self.assertIn("prompt-result-toast", ui_js)
        self.assertIn('data-action="view">点击查看', ui_js)
        self.assertIn("prompt-result-language", ui_js)
        self.assertIn("prompt_zh", ui_js)
        self.assertIn("function _cleanPromptResultChinese", ui_js)
        self.assertIn("function _dropEnglishPromptFragments", ui_js)
        self.assertIn("A-Za-z0-9'’._+/-", ui_js)
        self.assertIn("Original(?:\\s+prompt)?", ui_js)
        self.assertIn("prompt-tool-label", generate_js)
        self.assertIn("prompt-tool-btn-clear clear-btn", generate_js)
        self.assertIn("is-compact-disabled", generate_js)
        self.assertIn("disabled", generate_js)
        self.assertIn("trash-2", generate_js)
        self.assertIn("clearBtn.disabled = !hasText", ui_js)
        self.assertIn("optimizeBtn.disabled = !hasText", ui_js)
        self.assertIn("复制到输入框", ui_js)
        self.assertIn("is-copy hidden", ui_js)
        self.assertIn("closePromptResultToast", ui_js)
        self.assertIn("viewBtn.classList.add('hidden')", ui_js)
        self.assertNotIn("当前显示：", ui_js)

    def test_prompt_action_layout_contract(self):
        css = (ROOT / "static/css/style.css").read_text()

        self.assertIn(".toast.is-persistent", css)
        self.assertIn("top: calc(var(--titlebar-h) + 40px)", css)
        self.assertIn("--toast-accent-rgb", css)
        self.assertIn("--toast-bg", css)
        self.assertIn("background: var(--toast-bg)", css)
        self.assertIn("border-radius: 999px", css)
        self.assertIn(".toast::before", css)
        self.assertIn("display: none", css)
        self.assertIn(".prompt-result-toast", css)
        self.assertIn(".prompt-result-pending .toast-icon svg", css)
        self.assertIn(".toast-container.has-prompt-result-expanded", css)
        self.assertIn(".toast-container.has-prompt-result-active", css)
        self.assertIn("top: 83px", css)
        self.assertIn("width: 50vw", css)
        self.assertIn("width: min(96vw, 920px)", css)
        self.assertIn("max-height: min(62vh, 520px)", css)
        self.assertIn(".toast-container.has-prompt-result-expanded .prompt-result-toast.is-expanded", css)
        self.assertIn(".prompt-result-toast.is-expanded", css)
        self.assertIn("border-radius: 14px", css)
        self.assertIn(".prompt-result-controls", css)
        self.assertIn("padding-bottom: 10px", css)
        self.assertIn(".prompt-result-language", css)
        self.assertIn(".prompt-result-copy-row", css)
        self.assertIn(".prompt-tool-btn-vibrant .prompt-tool-label", css)
        self.assertIn("--prompt-tool-color: var(--accent)", css)
        self.assertIn("--prompt-tool-color: #22d3ee", css)
        self.assertIn("color: currentColor", css)
        self.assertIn(".prompt-tool-btn-clear", css)
        self.assertIn("--prompt-tool-color: #f87171", css)
        self.assertIn(".prompt-actions #optimizePromptBtn", css)
        self.assertIn("transition:", css)
        self.assertIn("max-width .22s cubic-bezier(.2,.78,.2,1)", css)
        self.assertIn(".prompt-tool-btn .prompt-tool-label", css)
        self.assertIn(".prompt-tool-btn.is-compact-disabled", css)
        self.assertIn("background-image: none !important", css)
        self.assertIn(".prompt-tool-btn.is-compact-disabled .prompt-tool-label", css)
        self.assertIn("animation: none !important", css)
        self.assertIn(".prompt-tool-btn:not(.prompt-tool-btn-vibrant):hover:not(:disabled)", css)
        self.assertIn("@keyframes promptToolBorderCycle", css)
        self.assertIn("repeating-linear-gradient(100deg", css)
        self.assertIn("background-origin: padding-box, border-box", css)
        self.assertIn("background-clip: padding-box, border-box", css)
        self.assertIn("220px 50%", css)
        self.assertNotIn("240% 50%", css)
        self.assertNotIn("promptToolShine", css)
        self.assertNotIn("promptToolTextCycle", css)
        self.assertNotIn("linear-gradient(135deg, rgba(17,35,68,.98)", css)
        self.assertIn(".prompt-interrogate-actions .prompt-tool-btn", css)
        self.assertIn(".prompt-interrogate-modal .prompt-interrogate-upload", css)
        self.assertIn(".prompt-interrogate-modal.open .prompt-interrogate-upload", css)
        self.assertIn("transform: translateY(10px)", css)
        self.assertIn("transition-delay: 60ms", css)
        self.assertIn("margin-left: auto", css)


if __name__ == "__main__":
    unittest.main()
